### ISSUE TITLE
connect timeout kills communicator thread

### ISSUE THREAD

**Issue by subes** [FXCMAPI/JavaAPI#1]
```
2019-10-17 14:58:40.670 [ |com.fxcm.messaging.] ERROR c.f.m.util.pdas.communicator.Communicator.request            - connect timed out
com.fxcm.messaging.util.CommunicationException: connect timed out
	at com.fxcm.messaging.util.pdas.communicator.http.HttpCommunicator.httpSend(HttpCommunicator.java:334)
	at com.fxcm.messaging.util.pdas.communicator.http.HttpCommunicator.trnSend(HttpCommunicator.java:128)
	at com.fxcm.messaging.util.pdas.communicator.Communicator.request(Communicator.java:438)
	at com.fxcm.messaging.util.pdas.communicator.Communicator.run(Communicator.java:327)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-10-17 14:58:40.670 [ |com.fxcm.messaging.] ERROR c.f.m.util.pdas.communicator.Communicator.request            - connect timed out: Message type=U54
112=EUDEMO_7F5BEED750BE7FE2E053E12B3C0AF9DA_10172019125324037086_YOR-472
336=FXCM
9016=list
--------
1:	9018=0;9017=BrcastID;
2:	9018=0;9017=MsgID;
3:	9018=0;9017=MailID;
4:	9018=1;9017=MessageFlags;
5:	9018=3000;9017=TimeOut;
--------
9028=0
625=EUDEMO
WaitTime=3000
SID=EUDEMO_7F5BEED750BE7FE2E053E12B3C0AF9DA_10172019125324037086_YOR
```

It would be nice if the library was able to recover from this, instead of having to close the current gateway from the outside and having to create a new one where the thread then runs again.

**Comment by subes** [comment]
After the connect timeout, the communicator will not work on any more messages without isConnected property telling if the connection broke. Thus maybe also check if the communicatorThread.isAlive() inside isConnected?

**Comment by fxcm-dhalpert** [comment]
did you tried to check isConnected() inside catch {} block.

**Comment by subes** [comment]
Yes, I verified this just now, though my catch block is where my timoutexception for the async request occurs. I don't have any way to modify a catch block inside HttpCommunicator/Communicator. Though the code is quite obvious to confirm my suspicion that isConnected should have been true.

```
2019-10-18 10:52:52.044 [ |com.fxcm.messaging.] ERROR c.f.m.util.pdas.communicator.Communicator.request            - connect timed out
com.fxcm.messaging.util.CommunicationException: connect timed out
	at com.fxcm.messaging.util.pdas.communicator.http.HttpCommunicator.httpSend(HttpCommunicator.java:334)
	at com.fxcm.messaging.util.pdas.communicator.http.HttpCommunicator.trnSend(HttpCommunicator.java:128)
	at com.fxcm.messaging.util.pdas.communicator.Communicator.request(Communicator.java:438)
	at com.fxcm.messaging.util.pdas.communicator.Communicator.run(Communicator.java:327)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-10-18 10:52:52.045 [ |com.fxcm.messaging.] ERROR c.f.m.util.pdas.communicator.Communicator.request            - connect timed out: Message type=V
9014=20191017
9015=12:46:05.732
9012=20191017
9100=true
9013=12:00:00.000
9011=0
262=EUDEMO_7F5BEED825017FE2E053E12B3C0AF9DA_10182019084823314334_74V-516
9074=U55
SID=EUDEMO_7F5BEED825017FE2E053E12B3C0AF9DA_10182019084823314334_74V
263=0
9075=
264=1
265=0
386=list
--------
1:	336=FXCM;625=EUDEMO;
--------
267=list
--------
--------
146=list
--------
1:	55=EUR/USD;9001=0;9000=0;
--------
336=FXCM
625=EUDEMO


2019-10-18 10:52:52.045 [ |com.fxcm.messaging.] WARN  d.i.t.s.trigger.SynchronizedStrategyTrigger.onLogMessage     - Error(-2): problem on communication request: connect timed out
2019-10-18 10:52:52.048 [ |BackToUserQueue    ] WARN  d.i.t.fxcm.gateway.internal.GatewayHandler.warn              - Unhandled message: BusinessMessageReject{mBusinessRejectReason=ACode{msCode=0,msLabel=Other,msDesc=Other},mFXCMErrorDetails=problem on communication request: connect timed out:FXCMRequestReject msTestReqID=null,msTradingSessionID=FXCM,msTradingSessionSubID=EUDEMO,msFXCMCommandID=0,mParams={ LIST_ID=EUDEMO_7F5BEED825017FE2E053E12B3C0AF9DA_10182019084823314334_74V-516;SID=EUDEMO_7F5BEED825017FE2E053E12B3C0AF9DA_10182019084823314334_74V},mDBAlias=null,mEntityCode=null,mResponseEncoding=null,mRequestBusID=null,mMessageBusID=null,mDatabaseBusID=null,mCustomBusID=null,mRequestorID=null,mSessionID=EUDEMO_7F5BEED825017FE2E053E12B3C0AF9DA_10182019084823314334_74V,mTransactTime=null,miFXCMRequestReject=-1,msText=problem on communication request: connect timed out,msFXCMErrorDetails=problem on communication request: connect timed out,mRefMsgType=null,mFXCMRequestRejectReason=-1,mBusinessRejectRefID=null,mRefMsgType=j,mText=problem on communication request: connect timed out,mTradingSessionID=null,mTradingSessionSubID=null}
2019-10-18 10:53:21.921 [ |7-1:FxcmLiveCalcula] INFO  d.i.trading.fxcm.gateway.GatewaySession.reconnect            - Reconnecting... (isConnected=true)
```


```java
    private IGateway gateway;

    public synchronized boolean isConnected() {
        return gateway != null && gateway.isConnected();
    }

    public void reconnect() throws RetryLaterException {
        if (reconnectLock.tryLock()) {
            try {
                try {
                    FTimeUnit.SECONDS.sleep(30);
                } catch (final InterruptedException e) {
                    throw new RuntimeException(e);
                }
                log.info("Reconnecting... (isConnected=" + isConnected() + ")");
                synchronized (this) {
                    close();
                    login();
                }
            } finally {
                reconnectLock.unlock();
            }
        } else {
            reconnectLock.lock();
            reconnectLock.unlock();
        }
    }

    public Callable<Collection<ITickData>> getTicks(final FxcmInstrument instrument, final FDate from, final FDate to,
            final Integer maxCount) {
        if (from.isAfterOrEqualToNotNullSafe(to)) {
            return EMPTY_CALLABLE;
        }
        return new ARetryingCallable<Collection<ITickData>>(
                new RetryOriginator(GatewaySession.class, "getTicks", instrument, from, to, maxCount)) {
            @Override
            protected Collection<ITickData> callRetryable() throws Exception {
                try {
                    return finalizer.handler.getMarketData()
                            .getTicks(instrument, from, to, maxCount)
                            .get(FxcmProperties.REQUEST_TIMEOUT.longValue(),
                                    FxcmProperties.REQUEST_TIMEOUT.getTimeUnit().timeUnitValue());
                } catch (final Throwable t) {
                    reconnect();
                    throw new RetryLaterException("Retrying after reconnect", t);
                }
            }
        };
    }
```

**Comment by subes** [comment]
Also I noticed that when I increase the amount of parallel market data requests in order to utilize more bandwidth, then the timeouts do not occur as likely. They happen very regularly when always having only one MarketDataRequest active in parallel.

**Comment by subes** [comment]
Also it seems this is likely caused by:
sun.net.client.defaultConnectTimeout=30000
sun.net.client.defaultReadTimeout=30000

When running with:
sun.net.client.defaultConnectTimeout=-1 (default: -1)
sun.net.client.defaultReadTimeout=-1 (default: -1)
(https://docs.oracle.com/javase/7/docs/technotes/guides/net/properties.html)

The timeout exception inside HttpCommunicator does not occur (though it still times out on my end but a retry then is successfull, only that one timed out message is just lost). Though it is a bad idea to rely on defaults (-1 timouts) in a client library. I prefer to not have processes stuck, instead to recover from stale connections. That's why I always use a socket timeout of 30 seconds or something similar as the default.

**Comment by fxcm-dhalpert** [comment]
can you please provide details on how to replicate this issue, 
you can also email us directly to api@fxcm.com

**Comment by subes** [comment]
I verified that you can reproduce this using this modified version of your HistoryMiner example:

Just replace the login credentials in the main method with a valid demo account. Then just wait a few minutes and the connect timeout exception will be thrown and the test will become stale (you will also notice that in the network monitor, the traffic goes from ~100kb to 0 before this happens). If you cannot reproduce it in the first run, just retry running it until the problem occurs. Though for me this happens during every run after a while. 

```java
// CHECKSTYLE:OFF
package com.fxcm.strategy.rsi.priceretrieve;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.SortedSet;
import java.util.TimeZone;
import java.util.TreeSet;

import com.fxcm.external.api.transport.FXCMLoginProperties;
import com.fxcm.external.api.transport.GatewayFactory;
import com.fxcm.external.api.transport.IGateway;
import com.fxcm.external.api.transport.listeners.IGenericMessageListener;
import com.fxcm.external.api.transport.listeners.IStatusMessageListener;
import com.fxcm.fix.FXCMTimingIntervalFactory;
import com.fxcm.fix.IFXCMTimingInterval;
import com.fxcm.fix.IFixDefs;
import com.fxcm.fix.Instrument;
import com.fxcm.fix.SubscriptionRequestTypeFactory;
import com.fxcm.fix.UTCDate;
import com.fxcm.fix.UTCTimeOnly;
import com.fxcm.fix.UTCTimestamp;
import com.fxcm.fix.pretrade.MarketDataRequest;
import com.fxcm.fix.pretrade.MarketDataRequestReject;
import com.fxcm.fix.pretrade.MarketDataSnapshot;
import com.fxcm.fix.pretrade.TradingSessionStatus;
import com.fxcm.messaging.ISessionStatus;
import com.fxcm.messaging.ITransportable;

// @NotThreadSafe
public class HistoryMiner implements IGenericMessageListener, IStatusMessageListener {
    private static final IFXCMTimingInterval TIMING = FXCMTimingIntervalFactory.TICK;
    private static final String server = "http://www.fxcorporate.com/Hosts.jsp";
    private final Instrument asset;
    private final UTCDate startDate;
    private final UTCTimeOnly startTime;
    private final FXCMLoginProperties login;

    private IGateway gateway;
    private String currentRequest;
    private final HashMap<UTCDate, MarketDataSnapshot> historicalRates = new HashMap<>();
    private int dataCounter = 0;
    public List<CandleStick> candlesticksList = new ArrayList<CandleStick>();

    private UTCTimestamp openTimestamp;
    public boolean stillMining = true;

    public HistoryMiner(final String username, final String password, final String terminal, final UTCDate startDate,
            final UTCTimeOnly startTime, final Instrument asset) {
        this.asset = asset;
        this.startDate = startDate;
        this.startTime = startTime;
        // create a local LoginProperty
        this.login = new FXCMLoginProperties(username, password, terminal, server);
    }

    // HistoryMIner.java continued...
    public boolean login(final IGenericMessageListener genericMessageListener,
            final IStatusMessageListener statusMessageListener) {
        try {
            if (gateway == null) {
                gateway = GatewayFactory.createGateway();
            }
            gateway.registerGenericMessageListener(genericMessageListener);
            gateway.registerStatusMessageListener(statusMessageListener);
            if (!gateway.isConnected()) {
                gateway.login(this.login);
            }
            currentRequest = gateway.requestTradingSessionStatus();
            // return that this process was successful
            return true;
        } catch (final Exception e) {
            e.printStackTrace();
        }
        // if any error occurred, then return that this process failed
        return false;
    }

    @Override
    public void messageArrived(final ISessionStatus status) {
        // check the status code
        if (status.getStatusCode() == ISessionStatus.STATUSCODE_ERROR
                || status.getStatusCode() == ISessionStatus.STATUSCODE_DISCONNECTING
                || status.getStatusCode() == ISessionStatus.STATUSCODE_CONNECTING
                || status.getStatusCode() == ISessionStatus.STATUSCODE_CONNECTED
                || status.getStatusCode() == ISessionStatus.STATUSCODE_CRITICAL_ERROR
                || status.getStatusCode() == ISessionStatus.STATUSCODE_EXPIRED
                || status.getStatusCode() == ISessionStatus.STATUSCODE_LOGGINGIN
                || status.getStatusCode() == ISessionStatus.STATUSCODE_LOGGEDIN
                || status.getStatusCode() == ISessionStatus.STATUSCODE_PROCESSING
                || status.getStatusCode() == ISessionStatus.STATUSCODE_DISCONNECTED) {
            // display status message System.out.println("\t\t" +
            // status.getStatusMessage());
        }
    }

    @Override
    public void messageArrived(final ITransportable message) {
        // decide which child function to send a cast instance of the message
        try {
            if (message instanceof MarketDataSnapshot) {
                messageArrived((MarketDataSnapshot) message);
            }
            if (message instanceof MarketDataRequestReject) {
                messageArrived((MarketDataRequestReject) message);
            } else if (message instanceof TradingSessionStatus) {
                messageArrived((TradingSessionStatus) message);
            }
        } catch (final Exception e) {
            e.printStackTrace();
        }
    }

    // HistoryMIner.java continued...
    public void messageArrived(final TradingSessionStatus tss) {
        if (currentRequest.equals(tss.getRequestID())) {
            final MarketDataRequest mdr = new MarketDataRequest();
            // set the subscription type to ask for only a snapshot of the
            // history
            mdr.setSubscriptionRequestType(SubscriptionRequestTypeFactory.SNAPSHOT);
            // request the response to be formated FXCM style
            mdr.setResponseFormat(IFixDefs.MSGTYPE_FXCMRESPONSE);
            // set the interval of the data candles
            mdr.setFXCMTimingInterval(TIMING);
            mdr.setFXCMStartDate(startDate);
            mdr.setFXCMStartTime(startTime);
            mdr.addRelatedSymbol(asset);
            // send request for historical data
            currentRequest = sendRequest(mdr);
        }
    }

    public String sendRequest(final MarketDataRequest request) {
        try {
            // send the request message to the API.
            currentRequest = gateway.sendMessage(request);
            // return the request id for authentication when messages would
            // arrive from the API.
            return currentRequest;
        } catch (final Exception e) {
            e.printStackTrace();
        }
        // if an error occurred, return no result
        return null;
    }

    public void logout(final IGenericMessageListener genericMessageListener,
            final IStatusMessageListener statusMessageListener) {
        // attempt to logout of the api
        gateway.logout();
        // remove the generic message listener, stop listening to updates
        gateway.removeGenericMessageListener(genericMessageListener);
        // remove the status message listener, stop listening to status changes
        gateway.removeStatusMessageListener(statusMessageListener);
    }

    // HistoryMIner.java continued...
    public void messageArrived(final MarketDataSnapshot mds) {
        if (mds.getRequestID() != null && mds.getRequestID().equals(currentRequest)) {
            historicalRates.put(mds.getDate(), mds);
        }
        if (mds.getRequestID() != null) {
            dataCounter++;
            if (openTimestamp == null) {
                // get the time stamp of first candle of this batch. use it to
                // set the end time of next batch.
                openTimestamp = mds.getOpenTimestamp();
                System.out.println("first\t= " + mds.getOpenTimestamp() + " = " + mds.getRequestID());
            }
            if (mds.getFXCMContinuousFlag() == IFixDefs.FXCMCONTINUOUS_END) { // end
                                                                              // of
                                                                              // packet.
                System.out.println("last\t= " + mds.getOpenTimestamp() + " = " + mds.getRequestID() + "\n");
                final MarketDataRequest mdr = new MarketDataRequest();
                mdr.setSubscriptionRequestType(SubscriptionRequestTypeFactory.SNAPSHOT);
                mdr.setResponseFormat(IFixDefs.MSGTYPE_FXCMRESPONSE);
                mdr.setFXCMTimingInterval(TIMING);
                mdr.setFXCMStartDate(startDate);
                mdr.setFXCMStartTime(startTime);
                mdr.setFXCMEndDate(new UTCDate(openTimestamp));
                mdr.setFXCMEndTime(new UTCTimeOnly(openTimestamp));
                mdr.addRelatedSymbol(asset);
                System.out.println("FXCMStartDate\t= " + mdr.getFXCMStartDate());
                System.out.println("FXCMStartTime\t= " + mdr.getFXCMStartTime());
                System.out.println("FXCMEndDate\t\t= " + mdr.getFXCMEndDate());
                System.out.println("FXCMEndTime\t\t= " + mdr.getFXCMEndTime());
                System.out.println("-----------------------\ntotal mds received = " + dataCounter + "\n");
                if (!(mds.getOpenTimestamp().equals(openTimestamp))) {
                    // send another request for historical data
                    currentRequest = sendRequest(mdr);
                    openTimestamp = null;
                } else {
                    stillMining = false;
                    System.out.println("mining over...");
                }
            }
        }
    }

    public void messageArrived(final MarketDataRequestReject mdrr) {
        System.out.println("Historical data rejected; " + mdrr.getMDReqRejReason());
        stillMining = false;
    }

    // HistoryMIner.java continued...
    public void convertHistoricalRatesToCandleSticks() {
        // get the keys of the historicalRates map into a sorted list
        final SortedSet<UTCDate> dateList = new TreeSet<>(historicalRates.keySet());
        // define a format for the dates
        final SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
        // make the date formatter above convert from GMT to BST
        sdf.setTimeZone(TimeZone.getTimeZone("Europe/London"));
        for (final UTCDate date : dateList) {
            MarketDataSnapshot candleData;
            candleData = historicalRates.get(date);
            // convert the key to a Date
            final Date candleDate = date.toDate();
            final String sdfDate = sdf.format(candleDate);
            final double open = candleData.getBidOpen();
            final double low = candleData.getBidLow();
            final double high = candleData.getAskHigh(); // ask is the relevant price
            // for short positions
            final double close = candleData.getBidClose();
            final CandleStick candlestick = new CandleStick(sdfDate, open, low, high, close);
            candlesticksList.add(candlestick);
        }
    }

    public void displayHistory() {
        if (candlesticksList.size() < 1) {
            System.out.println("No data do display");
            return;
        }
        // give the table column headings
        System.out.println("Date\t Time\t\tOBid\tCBid\tHBid\tLBid");
        for (final CandleStick candlestick : candlesticksList) {
            System.out.println(candlestick);
            //System.out.println( candlestick.getDate() + "\t" + candlestick.getOpen() + "\t" +  candlestick.getHigh() + "\t" +  candlestick.getLow() + "\t" +  candlestick.getCloseBid());
        }
    }

    public class CandleStick {
        private String date;
        private double open;
        private double low;
        private double high;
        private double close;
        private double rsi;

        public CandleStick(final String date, final double open, final double low, final double high,
                final double close) {
            this.date = date;
            this.open = open;
            this.low = low;
            this.high = high;
            this.close = close;

        }

        public double getRsi() {
            return rsi;
        }

        public void setRsi(final double rsi) {
            this.rsi = rsi;
        }

        public String getDate() {
            return date;
        }

        public void setDate(final String date) {
            this.date = date;
        }

        public double getOpen() {
            return open;
        }

        public void setOpen(final double open) {
            this.open = open;
        }

        public double getLow() {
            return low;
        }

        public void setLow(final double low) {
            this.low = low;
        }

        public double getHigh() {
            return high;
        }

        public void setHigh(final double high) {
            this.high = high;
        }

        public double getClose() {
            return close;
        }

        public void setClose(final double close) {
            this.close = close;
        }

        // getters and setters goes here...
        @Override
        public String toString() {
            return "CandleStick [date=" + date + ", open=" + open + ", low=" + low + ",high=" + high + ", close="
                    + close + "]";
        }
    }

    public static void main(final String[] args) {
        System.setProperty("sun.net.client.defaultConnectTimeout", "30000");
        System.setProperty("sun.net.client.defaultReadTimeout", "30000");
        UTCDate startDate;
        UTCTimeOnly startTime;
        final Instrument asset = new Instrument("EUR/USD");
        // get the current time and roll back 1 year
        final Calendar instance = Calendar.getInstance();
        instance.roll(Calendar.YEAR, -10);
        // set the starting date and time of the historical data
        startDate = new UTCDate(instance.getTime());
        startTime = new UTCTimeOnly(instance.getTime());
        try {
            // create an instance of the JavaFixHistoryMiner
            final HistoryMiner miner = new HistoryMiner("D102185580001", "1404", "Demo", startDate, startTime, asset);
            // login to the api
            miner.login(miner, miner);
            // keep mining for historical data before logging out
            while (miner.stillMining) {
                Thread.sleep(1000);
            }
            Thread.sleep(1000);
            // log out of the api
            miner.logout(miner, miner);
            // convert rates to candlesticks
            miner.convertHistoricalRatesToCandleSticks();
            // display the collected rates
            miner.displayHistory();
        } catch (final Exception e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by subes** [comment]
Just verified that the timeouts also occur with higher parallelity, so should be actually unrelated to that.

**Comment by Letob** [comment]
2020/01/21 08:25:23:378 CET [DEBUG] ExecutionReportProcessor - OrdStatus              = OrdStatus:REJECTED (8)
2020/01/21 08:25:23:378 CET [DEBUG] ExecutionReportProcessor - OrderQty               = 0
2020/01/21 08:25:23:378 CET [DEBUG] ExecutionReportProcessor - CumQty                 = 0
2020/01/21 08:25:23:378 CET [DEBUG] ExecutionReportProcessor - LastQty                = 0
2020/01/21 08:25:23:378 CET [DEBUG] ExecutionReportProcessor - LeavesQty              = 0
2020/01/21 08:25:23:378 CET [DEBUG] ExecutionReportProcessor - ********************************************
2020/01/21 08:25:23:379 CET [DEBUG] RequestForPositionsProcessor - RequestID = EUREAL_7F5C224CCC488AD1E053DF2B3C0A5A66_01212020072508725670_OIY-19; FXCMCommand = 67; Params={TraderID=62489, QID=EUREAL_7F5C224CCC488AD1E053DF2B3C0A5A66_01212020072508725670_OIY-19, SID=EUREAL_7F5C224CCC488AD1E053DF2B3C0A5A66_01212020072508725670_OIY, AcctReportID=all}
2020/01/21 08:25:23:379 CET [DEBUG] TradingServerSession - mClosedPositionMassID = EUREAL_7F5C224CCC488AD1E053DF2B3C0A5A66_01212020072508725670_OIY-19
2020/01/21 08:25:23:870 CET [DEBUG] FixFXMsgParser - parsing closed positions batch message = 0

2020/01/21 08:25:23:870 CET [DEBUG] FixFXMsgParser - parsing closed trade message = 0
2020/01/21 08:25:23:870 CET [DEBUG] RequestForPositionsAckProcessor - client: inc req pos ack = RequestForPositionsAck{mAccount='all', mFXCMErrorDetails='No close positions in response', mFXCMRequestRejectReason=2, mParties=Parties [Party:3:D:FXCM ID();], mPosReqID='EUREAL_7F5C224CCC488AD1E053DF2B3C0A5A66_01212020072508725670_OIY-19', mPosReqResult=PosReqResult:No positions found that match criteria (2), mPosReqStatus=PosReqStatus:Rejected (2), mText='No trades in response', mTotalNumPosReports=0, mTradingSessionID='FXCM', mTradingSessionSubID='EUREAL', mPosMaintRptID='0', mMakingTime=1579591523870}
2020/01/21 08:48:50:483 CET [ERROR] Communicator - Connection timed out: connect <com.fxcm.messaging.util.CommunicationException: Connection timed out: connect>com.fxcm.messaging.util.CommunicationException: Connection timed out: connect
	at com.fxcm.messaging.util.pdas.communicator.http.HttpCommunicator.httpSend(HttpCommunicator.java:334)
	at com.fxcm.messaging.util.pdas.communicator.http.HttpCommunicator.trnSend(HttpCommunicator.java:128)
	at com.fxcm.messaging.util.pdas.communicator.Communicator.request(Communicator.java:438)
	at com.fxcm.messaging.util.pdas.communicator.Communicator.run(Communicator.java:327)
	at java.lang.Thread.run(Unknown Source)

2020/01/21 08:48:50:484 CET [ERROR] Communicator - Connection timed out: connect: Message type=U54
112=EUREAL_7F5C224CCC488AD1E053DF2B3C0A5A66_01212020072508725670_OIY-2081
336=FXCM
9016=list
--------
1:	9018=0;9017=BrcastID;
2:	9018=0;9017=MsgID;
3:	9018=0;9017=MailID;
4:	9018=894;9017=MessageFlags;
5:	9018=3000;9017=TimeOut;
--------
9028=0
625=EUREAL
WaitTime=3000
SID=EUREAL_7F5C224CCC488AD1E053DF2B3C0A5A66_01212020072508725670_OIY

Hi, is there any solution for that problem, it's come very often and i do not know how to relaunch gateway session ?
Trying defaultConnectTimeout=-1 failed !
I'm using JTS J3 but in my case i've open multi session from 3 computers for debug purpose
Thank's a lot.

**Comment by fxcm-dhalpert** [comment]
can you please email your username, OS version, Java version to api@fxcm.com

**Comment by Letob** [comment]
Hi !
email : ledayoux@hotmail.com
username : Letob
OS : Windows 10 PRO 64 bit
JAVA : 1.8.0_231

Best regards


Envoyé à partir d’Outlook<http://aka.ms/weboutlook>

________________________________
De : Daniel Halpert <notifications@github.com>
Envoyé : mardi 21 janvier 2020 12:25
À : fxcm/JavaAPI <JavaAPI@noreply.github.com>
Cc : Letob <ledayoux@hotmail.com>; Comment <comment@noreply.github.com>
Objet : Re: [fxcm/JavaAPI] connect timeout kills communicator thread (#1)


can you please email your username, OS version, Java version to api@fxcm.com<mailto:api@fxcm.com>
